sonarqube-check:
    image:
        name: sonarsource/sonar-scanner-cli:latest
        entrypoint: [""]
    variables:
        SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
        SONAR_TOKEN: ${SONAR_TOKEN}
        SONAR_HOST_URL: ${SONAR_HOST_URL}
        GIT_DEPTH: 0
    cache:
        key: "${CI_JOB_NAME}"
        paths:
            - .sonar/cache
    tags:
        - sonarqube
    script:
        - sonar-scanner -X -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.qualitygate.wait=true -Dsonar.projectKey=${CI_PROJECT_NAME} -Dsonar.projectVersion=${CI_COMMIT_SHORT_SHA} -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID
    allow_failure: true
